unifabric:
  adapter:
    host: 172.30.23.95
    name: docker-adapter-01
    description: "本机 Docker 资源适配器"
    type: docker
    zone: ""
    registry:
      host: 127.0.0.1
      port: 9090
    tags:
      - cpu
      - memory
    docker:
      host: unix:///var/run/docker.sock
      network: ""
    k8s:
      kubeconfig: ""
      in-cluster: false
      namespace: default
    connectivity:
      proxy-port-min: 0
      proxy-port-max: 0
